tasks:
  - name: Script Task
    before: cd ./application
    command: |
      npm i
      npm run dev
      cd ..
  
  - name: Setup backend
    before: cd ./backend
    command: |
      npm i
      node app.js
      cd ..
